# Generated by Django 2.2.2 on 2019-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='opis',
            field=models.TextField(default='dodaj opis'),
            preserve_default=False,
        ),
    ]
