# Generated by Django 2.2.2 on 2019-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0002_car_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='opis',
            field=models.TextField(default='Dodaj opis'),
        ),
    ]
